---
# file: roles/common/tasks/main.yml

- name: Install packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - debootstrap
    - sudo

- name: Add key for Docker repo
  apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D

- name: add docker repo
  apt_repository: repo='deb https://apt.dockerproject.org/repo debian-jessie main' state=present update_cache=yes

- name: Apt-get update and upgrade
  apt: update_cache=yes upgrade=dist

- name: Install Docker
  apt: name=docker-engine state=present
  notify:
    - start docker
